language: go

# Sudo is required for docker
sudo: required

go:
  - 1.7.x
  - 1.8.x
  - master

services:
  - docker

before_install:
 - go get github.com/tools/godep

install:
 - godep restore

after_success:
  - bash <(curl -s https://codecov.io/bash)